**Task11.1/Docker**
<br>

**Simple container:**
<br>
Dockerfile content:
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/dockfile1.jpg">
<br>
Build and run container:
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/build.jpg">
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/run.jpg">
<br>
Result:
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/res1.jpg">
<br>

**Docker with Pyton Webapps:**
<br>
App directory:
<br>
```
mkdir flask-app
cd flask-app/
nano app.py
nano requirements.txt
mkdir templates
cd templates/
nano index.html
nano Dockerfile	
```
<br>
App.py contents images:
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/py.jpg">
<br>
Dockefile configurations:
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/dockfile2.jpg">
<br>
index.html content:
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/html.jpg">
<br>
Server recieves connect requests...but something went wrong(
<br>
<img src="https://github.com/HighLandner/DevOps_online_Kharkiv_2021Q1/blob/master/m11/task11.1/images/res2.jpg">
<br>

